name: linting-and-testing
on: push
jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Cloning the repository
        uses: actions/checkout@v2

      - name: Installing node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing project dependencies
        run: make install

      - name: Linting
        run: make lint

      - name: Testing
        run: make test

      - name: Reporting test-coverage to Codeclimate
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true